name: Build CPP Libs

on: [push, pull_request]
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
  USER_CONFIG: ${{github.workspace}}/.github/config/boost/user-config.jam

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4

        # Output build artifacts to /github/workspace on the container.
        - name: Build action
          uses: ./ # Uses an action in the root directory
          id: build

        - name: Upload Build Artifacts
          uses: actions/upload-artifact@v4
          with:
            name: workspace_artifacts
            path: ${{ github.workspace }}/run
